# All the actions will be executed only if the commit happens on main branch
name: CI-Non-MAIN-Branch
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Running SAST Scan
        run: echo "Running Static Application Security Testing" 

  test:
    runs-on: self-hosted
    needs: scan
    steps:
      - uses: actions/checkout@v4
      - name: Running Test Cases
        run: echo "Running Unit + Integration Testing"
